server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3

rabbitmq:
  proposta-pendente:
    exchange: "proposta-pendente.ex"
    ms-analise-credito:
      queue: "proposta-pendente.ms-analise-credito"
      dlq: "proposta-pendente.ms-analise-credito.dlq"
      dlx: "proposta-pendente.ms-analise-credito.dlx"
  proposta-concluida:
    exchange: "proposta-concluida.ex"