spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  proposta-pendente:
    queue: "proposta-pendente.ms-analise-credito"
  proposta-concluida:
    exchange: "proposta-concluida.ex"