server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
  proposta-pendente:
    exchange: "proposta-pendente.ex"
    ms-notificacao:
      queue: "proposta-pendente.ms-notificacao"
  proposta-concluida:
    exchange: "proposta-concluida.ex"
    ms-notificacao:
      queue: "proposta-concluida.ms-notificacao"
